version: "2"

linters:
  default: standard
  enable:
    - cyclop
    - gocognit
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - cyclop
          - gocognit
  settings:
    cyclop:
      max-complexity: 20
      package-average: 0.0
    gocognit:
      min-complexity: 31
